# Generated by Django 5.0.3 on 2024-03-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calidad_peligro', models.CharField(max_length=100)),
                ('calidad_riesgo', models.CharField(max_length=100)),
                ('calidad_causas', models.CharField(max_length=100)),
                ('calidad_control', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('operativo_equipos', models.CharField(max_length=100)),
                ('operativo_materiales', models.CharField(max_length=100)),
                ('operativo_herramientas', models.CharField(max_length=100)),
                ('operativo_manodeobra', models.CharField(max_length=100)),
                ('operativo_epps', models.CharField(max_length=100)),
                ('operativo_generales', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('seguridad_peligro', models.CharField(max_length=100)),
                ('seguridad_riesgo', models.CharField(max_length=100)),
                ('seguridad_control', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=100)),
                ('objeto', models.CharField(max_length=100)),
                ('orden_de_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('recurso_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='modelos.recursocalidad')),
                ('recurso_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='modelos.recursooperativo')),
                ('recurso_seguridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='modelos.recursoseguridad')),
            ],
        ),
    ]
