# Generated by Django 5.0.3 on 2024-03-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_alter_recursocalidad_calidad_causas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursoseguridad',
            old_name='nombre',
            new_name='clase_seguridad',
        ),
    ]
