# Generated by Django 5.0.3 on 2024-03-08 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_rename_nombre_recursoseguridad_clase_seguridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='recurso_calidad',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='recurso_operativo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='recurso_seguridad',
        ),
        migrations.CreateModel(
            name='TarjetaDeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('valorizacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tareas', models.ManyToManyField(related_name='tarjetas_de_control', to='modelos.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurso_calidad',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='modelos.recursocalidad'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurso_operativo',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='modelos.recursooperativo'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurso_seguridad',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='modelos.recursoseguridad'),
        ),
    ]
