# Generated by Django 5.0.3 on 2024-03-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_tarjetadecontrol_usuario'),
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='subproceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procesos.subproceso'),
        ),
    ]
