# Generated by Django 5.0.3 on 2024-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_tarea_subproceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='orden_de_venta',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo_tarea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='unidad_de_medida',
            field=models.CharField(blank=True, default='minutos', max_length=50),
        ),
    ]
