# Generated by Django 5.0.3 on 2024-04-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_remove_tarea_recurso_calidad_and_more'),
        ('planner', '0008_alter_tarjetadiaria_tareas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='TarjetaDeControl',
        ),
    ]
