# Generated by Django 5.0.3 on 2024-04-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidad', '0001_initial'),
        ('operativos', '0001_initial'),
        ('procesos', '0003_remove_subproceso_proceso_subproceso_proceso'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=100)),
                ('objeto', models.CharField(max_length=100)),
                ('unidad_de_medida', models.CharField(blank=True, default='minutos', max_length=50)),
                ('tiempo_tarea', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recurso_calidad', models.ManyToManyField(blank=True, related_name='tareas', to='calidad.recursocalidad')),
                ('recurso_operativo', models.ManyToManyField(blank=True, related_name='tareas', to='operativos.recursooperativo')),
                ('recurso_seguridad', models.ManyToManyField(blank=True, related_name='tareas', to='seguridad.recursoseguridad')),
                ('subproceso', models.ManyToManyField(related_name='tareas', to='procesos.subproceso')),
            ],
        ),
    ]
