# Generated by Django 5.0.3 on 2024-03-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
