# Generated by Django 5.0.3 on 2024-03-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_equipo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
