# Generated by Django 5.0.3 on 2024-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('jefe', 'Jefe')], max_length=100),
        ),
    ]
