# Generated by Django 5.0.3 on 2024-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='tipo',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Mejora', 'Mejora'), ('Requerimiento', 'Requerimiento')], default='Bug', max_length=15),
        ),
    ]
