# Generated by Django 5.0.3 on 2024-03-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_alter_userprofile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.userprofile')),
            ],
        ),
    ]
