# Generated by Django 5.0.3 on 2024-04-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_remove_tarea_subproceso_tarea_subproceso'),
        ('planner', '0003_tarjetadiaria_duracion_jornada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaOrdenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('tareaorden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.tarea')),
                ('tarjetadiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.tarjetadiaria')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
