# Generated by Django 5.0.3 on 2024-04-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_remove_tarea_subproceso_tarea_subproceso'),
        ('planner', '0004_tarjetaordendiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetadiaria',
            name='tareas',
        ),
        migrations.AddField(
            model_name='tarjetadiaria',
            name='tareas',
            field=models.ManyToManyField(blank=True, related_name='tarjetas_diarias', through='planner.TarjetaOrdenDiario', to='modelos.tarea'),
        ),
    ]
