# Generated by Django 5.0.3 on 2024-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_remove_tarea_subproceso_tarea_subproceso'),
        ('planner', '0005_alter_tarjetadiaria_tareas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetadiaria',
            name='tareas',
            field=models.ManyToManyField(blank=True, related_name='tarjetas_diarias', to='modelos.tarea'),
        ),
    ]
