# Generated by Django 5.0.3 on 2024-04-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_tarjetadiaria_tareas'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetadiaria',
            name='tareas',
            field=models.ManyToManyField(blank=True, related_name='tarjetas_diarias', to='tareas.tarea'),
        ),
        migrations.AlterField(
            model_name='tarjetaordendiario',
            name='tareaorden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea'),
        ),
    ]
